apiVersion: apps/v1
kind: Deployment
metadata:
  name: input-server
  labels:
    app: input-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: input-server
  template:
    metadata:
      labels:
        app: input-server
    spec:
      containers:
      - name: input-server
        image: input-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: OUTPUT_SERVICE_URL
          value: "http://output-server-service:3001"