apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html-content
  labels:
    {{- include "hello-world-chart.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Hello from Kubernetes!</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          background-color: #f4f4f4;
          margin: 0;
          padding: 20px;
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
        }
        .container {
          background: white;
          border-radius: 8px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
          padding: 40px;
          text-align: center;
          max-width: 600px;
        }
        h1 { color: #2266AA; margin-bottom: 20px; }
        .info { margin-top: 20px; color: #666; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>{{ .Values.appConfig.message }}</h1>
        <p>Your Kubernetes cluster is running properly with Helm!</p>
        <div class="info">
          <p>Release: {{ .Release.Name }}</p>
          <p>Namespace: {{ .Release.Namespace }}</p>
        </div>
      </div>
    </body>
    </html>