name: 2024-11-update-node-npm-yarn-pnpm-to-latest
run-name: 2024-11-update-node-npm-yarn-pnpm-to-latest.sh
on: [push]
jobs:
  update-node-npm-yarn-pnpm-to-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: echo ${{ github.actor }} 
      - run: echo update node npm yarn pnpm to latest
      - run: pwd 
      - run: ls
      - run: chmod +x bash/2024-11-update-node-npm-yarn-pnpm-to-latest.sh
      - run: bash/2024-11-update-node-npm-yarn-pnpm-to-latest.sh
